services:
  - type: web
    name: iitm-flask-app
    runtime: python
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip curl

      # Install Chrome dependencies
      apt-get install -y \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libu2f-udev \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxkbcommon0 \
        libxrandr2 \
        xdg-utils

      # Download & install Google Chrome (Render compatible)
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb || true

      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app:app
