services:
  - type: web
    name: iitm-flask-app
    runtime: python
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb || true
      pip install -r requirements.txt
    startCommand: gunicorn app:app
